apiVersion: v1
kind: Service
metadata:
  labels:
    app: database
  name: database
spec:
  type: NodePort
  ports:
  - name: "http"
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: database
